apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-corp
  description: The acme-corp organization
spec:
  type: organization
  children: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-groups
  description: A collection of all Backstage example Groups
spec:
  type: github
  targets:
    - https://github.com/ramcguire/gratibot-2/blob/master/group-a.yaml